spring.application.name=hubspot-integration
# =========================
# CONFIGURAÇÃO DO H2
# =========================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar os SQLs gerados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Atualiza/cria as tabelas com base nas entidades
spring.jpa.hibernate.ddl-auto=update

# Ativa o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# CONFIGURAÇÃO DO HUBSPOT
# =========================
hubspot.client-id=YOUR_CLIENT_ID
hubspot.client-secret=YOUR_CLIENT_SECRET
hubspot.grant-type=authorization_code
hubspot.redirect-uri=http://localhost:8080/oauth/callback
hubspot.api.base-url=https://api.hubapi.com
hubspot.token-uri=${hubspot.api.base-url}/oauth/v1/token
hubspot.scope=crm.objects.contacts.write crm.objects.contacts.read
hubspot.response-type=code
hubspot.contacts-uri=${hubspot.api.base-url}/crm/v3/objects/contacts
hubspot.authorization-uri=https://app.hubspot.com/oauth/authorize